# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "452c0f42cf636de5607c5851790be021"
application_url = "https://webshots-abandoned-lover-earliest.trycloudflare.com"
embedded = true
name = "test-app"
handle = "test-app-10904"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://webshots-abandoned-lover-earliest.trycloudflare.com/auth/callback",
  "https://webshots-abandoned-lover-earliest.trycloudflare.com/auth/shopify/callback",
  "https://webshots-abandoned-lover-earliest.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "loja-teste-shop-br.myshopify.com"
automatically_update_urls_on_dev = true
